//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAnalyticsMaui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientAnalyticsMaui.Resources.Localization.Localized_de", typeof(Localized_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patientenanalyse.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte versuchen Sie es erneut mit einer anderen Kombination aus Benutzername und Passwort.
        /// </summary>
        internal static string AuthError_LoginFailureMessage {
            get {
                return ResourceManager.GetString("AuthError_LoginFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung nicht möglich.
        /// </summary>
        internal static string AuthError_LoginFailureTitle {
            get {
                return ResourceManager.GetString("AuthError_LoginFailureTitle", resourceCulture);
            }
        }        
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist nicht möglich, Patienten zu bekommen.
        /// </summary>
        internal static string AuthError_UnableGetPatients {
            get {
                return ResourceManager.GetString("AuthError_UnableGetPatients", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Unerwartete Rolle.
        /// </summary>
        internal static string AuthError_UnexpectedRole {
            get {
                return ResourceManager.GetString("AuthError_UnexpectedRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Patient.
        /// </summary>
        public static string Button_DeletePatient
        {
            get
            {
                return ResourceManager.GetString("Button_DeletePatient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Bearbeiten.
        /// </summary>
        internal static string Button_EditPatient {
            get {
                return ResourceManager.GetString("Button_EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung.
        /// </summary>
        internal static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        internal static string Button_Logout {
            get {
                return ResourceManager.GetString("Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patienten.
        /// </summary>
        internal static string Button_Patient {
            get {
                return ResourceManager.GetString("Button_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratoren Ansehen.
        /// </summary>
        internal static string Button_ViewAdmins {
            get {
                return ResourceManager.GetString("Button_ViewAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ärzte Ansehen.
        /// </summary>
        internal static string Button_ViewDoctors {
            get {
                return ResourceManager.GetString("Button_ViewDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmins Ansehen.
        /// </summary>
        internal static string Button_ViewSuperAdmins {
            get {
                return ResourceManager.GetString("Button_ViewSuperAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy.
        /// </summary>
        internal static string DateFormatting_Date {
            get {
                return ResourceManager.GetString("DateFormatting_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd_hhmm.
        /// </summary>
        internal static string DateFormatting_DateTime {
            get {
                return ResourceManager.GetString("DateFormatting_DateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geduldig.
        /// </summary>
        internal static string Label_Patient {
            get {
                return ResourceManager.GetString("Label_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Blutdruckdatensatz mit der ID: {0} konnte nicht gefunden werden..
        /// </summary>
        internal static string PatientBloodPressureError_NotFound {
            get {
                return ResourceManager.GetString("PatientBloodPressureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesem Benutzer ist es untersagt, den Patienten mit der ID {0} anzuzeigen und zu ändern..
        /// </summary>
        internal static string PatientError_Forbidden {
            get {
                return ResourceManager.GetString("PatientError_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient mit ID: {0} konnte nicht gefunden werden.
        /// </summary>
        internal static string PatientError_NotFound {
            get {
                return ResourceManager.GetString("PatientError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Höhendatensatz mit der ID: {0} konnte nicht gefunden werden..
        /// </summary>
        internal static string PatientHeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientHeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Temperaturdatensatz mit der ID: {0} konnte nicht gefunden werden..
        /// </summary>
        internal static string PatientTemperatureError_NotFound {
            get {
                return ResourceManager.GetString("PatientTemperatureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Gewichtsdatensatz mit der ID: {0} konnte nicht gefunden werden..
        /// </summary>
        internal static string PatientWeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientWeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blutdruck.
        /// </summary>
        internal static string ReportTitles_BloodPressure {
            get {
                return ResourceManager.GetString("ReportTitles_BloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter BMI-Wert um {0}: {1}.
        /// </summary>
        internal static string ReportTitles_BMIEnd {
            get {
                return ResourceManager.GetString("ReportTitles_BMIEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste BMI-Messung um {0}: {1}.
        /// </summary>
        internal static string ReportTitles_BMIStart {
            get {
                return ResourceManager.GetString("ReportTitles_BMIStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe.
        /// </summary>
        internal static string ReportTitles_Height {
            get {
                return ResourceManager.GetString("ReportTitles_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht für Patienten {0} {1}.
        /// </summary>
        internal static string ReportTitles_Patient {
            get {
                return ResourceManager.GetString("ReportTitles_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patienten ID: {0}.
        /// </summary>
        internal static string ReportTitles_PatientID {
            get {
                return ResourceManager.GetString("ReportTitles_PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatur.
        /// </summary>
        internal static string ReportTitles_Temperatures {
            get {
                return ResourceManager.GetString("ReportTitles_Temperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewicht.
        /// </summary>
        internal static string ReportTitles_Weight {
            get {
                return ResourceManager.GetString("ReportTitles_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-Dashboard.
        /// </summary>
        internal static string Title_AdminDashboard {
            get {
                return ResourceManager.GetString("Title_AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        internal static string Title_Admins {
            get {
                return ResourceManager.GetString("Title_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arzt-Dashboard.
        /// </summary>
        internal static string Title_DoctorDashboard {
            get {
                return ResourceManager.GetString("Title_DoctorDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ärzte.
        /// </summary>
        internal static string Title_Doctors {
            get {
                return ResourceManager.GetString("Title_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ärzte Patienten.
        /// </summary>
        internal static string Title_DoctorsPatients {
            get {
                return ResourceManager.GetString("Title_DoctorsPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heim.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patienten-Dashboard.
        /// </summary>
        internal static string Title_PatientDashboard {
            get {
                return ResourceManager.GetString("Title_PatientDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patientenbearbeitungsseite.
        /// </summary>
        internal static string Title_PatientEditPage {
            get {
                return ResourceManager.GetString("Title_PatientEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patientenseite.
        /// </summary>
        internal static string Title_PatientPage {
            get {
                return ResourceManager.GetString("Title_PatientPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmins.
        /// </summary>
        internal static string Title_SuperAdmins {
            get {
                return ResourceManager.GetString("Title_SuperAdmins", resourceCulture);
            }
        }
    }
}
