//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAnalyticsMaui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientAnalyticsMaui.Resources.Localization.Localized_zh", typeof(Localized_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患者分析.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請使用不同的使用者名稱和密碼組合重試.
        /// </summary>
        internal static string AuthError_LoginFailureMessage {
            get {
                return ResourceManager.GetString("AuthError_LoginFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法登入.
        /// </summary>
        internal static string AuthError_LoginFailureTitle {
            get {
                return ResourceManager.GetString("AuthError_LoginFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法接診患者.
        /// </summary>
        internal static string AuthError_UnableGetPatients {
            get {
                return ResourceManager.GetString("AuthError_UnableGetPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意想不到的角色.
        /// </summary>
        internal static string AuthError_UnexpectedRole {
            get {
                return ResourceManager.GetString("AuthError_UnexpectedRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Patient.
        /// </summary>
        public static string Button_DeletePatient
        {
            get
            {
                return ResourceManager.GetString("Button_DeletePatient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯患者.
        /// </summary>
        internal static string Button_EditPatient {
            get {
                return ResourceManager.GetString("Button_EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        internal static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string Button_Logout {
            get {
                return ResourceManager.GetString("Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好的.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患者.
        /// </summary>
        internal static string Button_Patient {
            get {
                return ResourceManager.GetString("Button_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看管理員.
        /// </summary>
        internal static string Button_ViewAdmins {
            get {
                return ResourceManager.GetString("Button_ViewAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看醫生.
        /// </summary>
        internal static string Button_ViewDoctors {
            get {
                return ResourceManager.GetString("Button_ViewDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看超級管理員.
        /// </summary>
        internal static string Button_ViewSuperAdmins {
            get {
                return ResourceManager.GetString("Button_ViewSuperAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy.
        /// </summary>
        internal static string DateFormatting_Date {
            get {
                return ResourceManager.GetString("DateFormatting_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd_hhmm.
        /// </summary>
        internal static string DateFormatting_DateTime {
            get {
                return ResourceManager.GetString("DateFormatting_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 病人.
        /// </summary>
        internal static string Label_Patient {
            get {
                return ResourceManager.GetString("Label_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法找到 ID 為 {0} 的血壓記錄.
        /// </summary>
        internal static string PatientBloodPressureError_NotFound {
            get {
                return ResourceManager.GetString("PatientBloodPressureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此使用者沒有檢視和修改 ID 為：{0} 的患者的授權.
        /// </summary>
        internal static string PatientError_Forbidden {
            get {
                return ResourceManager.GetString("PatientError_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法找到 ID 為 {0} 的患者.
        /// </summary>
        internal static string PatientError_NotFound {
            get {
                return ResourceManager.GetString("PatientError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法找到 ID 為 {0} 的高度記錄.
        /// </summary>
        internal static string PatientHeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientHeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法找到 ID 為 {0} 的溫度記錄.
        /// </summary>
        internal static string PatientTemperatureError_NotFound {
            get {
                return ResourceManager.GetString("PatientTemperatureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法找到 ID 為 {0} 的體重記錄.
        /// </summary>
        internal static string PatientWeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientWeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血壓.
        /// </summary>
        internal static string ReportTitles_BloodPressure {
            get {
                return ResourceManager.GetString("ReportTitles_BloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最後 BMI 讀數為 {0}: {1}.
        /// </summary>
        internal static string ReportTitles_BMIEnd {
            get {
                return ResourceManager.GetString("ReportTitles_BMIEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一次 BMI 讀數 {0}: {1}.
        /// </summary>
        internal static string ReportTitles_BMIStart {
            get {
                return ResourceManager.GetString("ReportTitles_BMIStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高度.
        /// </summary>
        internal static string ReportTitles_Height {
            get {
                return ResourceManager.GetString("ReportTitles_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 給病人的報告 {0} {1}.
        /// </summary>
        internal static string ReportTitles_Patient {
            get {
                return ResourceManager.GetString("ReportTitles_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 病號 ID: {0}.
        /// </summary>
        internal static string ReportTitles_PatientID {
            get {
                return ResourceManager.GetString("ReportTitles_PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 溫度.
        /// </summary>
        internal static string ReportTitles_Temperatures {
            get {
                return ResourceManager.GetString("ReportTitles_Temperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重量.
        /// </summary>
        internal static string ReportTitles_Weight {
            get {
                return ResourceManager.GetString("ReportTitles_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理儀表板.
        /// </summary>
        internal static string Title_AdminDashboard {
            get {
                return ResourceManager.GetString("Title_AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理員.
        /// </summary>
        internal static string Title_Admins {
            get {
                return ResourceManager.GetString("Title_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 醫生儀表板.
        /// </summary>
        internal static string Title_DoctorDashboard {
            get {
                return ResourceManager.GetString("Title_DoctorDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 醫生.
        /// </summary>
        internal static string Title_Doctors {
            get {
                return ResourceManager.GetString("Title_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 醫生 病人.
        /// </summary>
        internal static string Title_DoctorsPatients {
            get {
                return ResourceManager.GetString("Title_DoctorsPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主頁.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患者儀表板.
        /// </summary>
        internal static string Title_PatientDashboard {
            get {
                return ResourceManager.GetString("Title_PatientDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患者編輯頁面.
        /// </summary>
        internal static string Title_PatientEditPage {
            get {
                return ResourceManager.GetString("Title_PatientEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患者頁面.
        /// </summary>
        internal static string Title_PatientPage {
            get {
                return ResourceManager.GetString("Title_PatientPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超級管理員.
        /// </summary>
        internal static string Title_SuperAdmins {
            get {
                return ResourceManager.GetString("Title_SuperAdmins", resourceCulture);
            }
        }
    }
}
