//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAnalyticsMaui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientAnalyticsMaui.Resources.Localization.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Analytics.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again with a different username and password combo.
        /// </summary>
        public static string AuthError_LoginFailureMessage {
            get {
                return ResourceManager.GetString("AuthError_LoginFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Login.
        /// </summary>
        public static string AuthError_LoginFailureTitle {
            get {
                return ResourceManager.GetString("AuthError_LoginFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string AuthError_LoginUserNotFoundTitle {
            get {
                return ResourceManager.GetString("AuthError_LoginUserNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string AuthError_LoginWrongPasswordTitle {
            get {
                return ResourceManager.GetString("AuthError_LoginWrongPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get patients.
        /// </summary>
        public static string AuthError_UnableGetPatients {
            get {
                return ResourceManager.GetString("AuthError_UnableGetPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Role.
        /// </summary>
        public static string AuthError_UnexpectedRole {
            get {
                return ResourceManager.GetString("AuthError_UnexpectedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Patient.
        /// </summary>
        public static string Button_DeletePatient {
            get {
                return ResourceManager.GetString("Button_DeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patient.
        /// </summary>
        public static string Button_EditPatient {
            get {
                return ResourceManager.GetString("Button_EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Button_Logout {
            get {
                return ResourceManager.GetString("Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Button_Patient {
            get {
                return ResourceManager.GetString("Button_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Admins.
        /// </summary>
        public static string Button_ViewAdmins {
            get {
                return ResourceManager.GetString("Button_ViewAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Doctors.
        /// </summary>
        public static string Button_ViewDoctors {
            get {
                return ResourceManager.GetString("Button_ViewDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View SuperAdmins.
        /// </summary>
        public static string Button_ViewSuperAdmins {
            get {
                return ResourceManager.GetString("Button_ViewSuperAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy.
        /// </summary>
        public static string DateFormatting_Date {
            get {
                return ResourceManager.GetString("DateFormatting_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd_hhmm.
        /// </summary>
        public static string DateFormatting_DateTime {
            get {
                return ResourceManager.GetString("DateFormatting_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Label_Patient {
            get {
                return ResourceManager.GetString("Label_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate blood pressure record with id: {0}.
        /// </summary>
        public static string PatientBloodPressureError_NotFound {
            get {
                return ResourceManager.GetString("PatientBloodPressureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is forbidden from viewing and modifying patient with id: {0}.
        /// </summary>
        public static string PatientError_Forbidden {
            get {
                return ResourceManager.GetString("PatientError_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate patient with id: {0}.
        /// </summary>
        public static string PatientError_NotFound {
            get {
                return ResourceManager.GetString("PatientError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate height record with id: {0}.
        /// </summary>
        public static string PatientHeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientHeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate temperature record with id: {0}.
        /// </summary>
        public static string PatientTemperatureError_NotFound {
            get {
                return ResourceManager.GetString("PatientTemperatureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate weight record with id: {0}.
        /// </summary>
        public static string PatientWeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientWeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        public static string ReportTitles_BloodPressure {
            get {
                return ResourceManager.GetString("ReportTitles_BloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last BMI Reading at {0}: {1}.
        /// </summary>
        public static string ReportTitles_BMIEnd {
            get {
                return ResourceManager.GetString("ReportTitles_BMIEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First BMI Reading at {0}: {1}.
        /// </summary>
        public static string ReportTitles_BMIStart {
            get {
                return ResourceManager.GetString("ReportTitles_BMIStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ReportTitles_Height {
            get {
                return ResourceManager.GetString("ReportTitles_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for patient {0} {1}.
        /// </summary>
        public static string ReportTitles_Patient {
            get {
                return ResourceManager.GetString("ReportTitles_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID: {0}.
        /// </summary>
        public static string ReportTitles_PatientID {
            get {
                return ResourceManager.GetString("ReportTitles_PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string ReportTitles_Temperatures {
            get {
                return ResourceManager.GetString("ReportTitles_Temperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string ReportTitles_Weight {
            get {
                return ResourceManager.GetString("ReportTitles_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string Title_AdminDashboard {
            get {
                return ResourceManager.GetString("Title_AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Title_Admins {
            get {
                return ResourceManager.GetString("Title_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Dashboard.
        /// </summary>
        public static string Title_DoctorDashboard {
            get {
                return ResourceManager.GetString("Title_DoctorDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Title_Doctors {
            get {
                return ResourceManager.GetString("Title_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors Patients.
        /// </summary>
        public static string Title_DoctorsPatients {
            get {
                return ResourceManager.GetString("Title_DoctorsPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Dashboard.
        /// </summary>
        public static string Title_PatientDashboard {
            get {
                return ResourceManager.GetString("Title_PatientDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Edit Page.
        /// </summary>
        public static string Title_PatientEditPage {
            get {
                return ResourceManager.GetString("Title_PatientEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Page.
        /// </summary>
        public static string Title_PatientPage {
            get {
                return ResourceManager.GetString("Title_PatientPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmins.
        /// </summary>
        public static string Title_SuperAdmins {
            get {
                return ResourceManager.GetString("Title_SuperAdmins", resourceCulture);
            }
        }
    }
}
